variables:
  - group: ssh-credentials
  - name: mergeCommit
    value: ""
  - name: modifiedDirectories
    value: ""

resources:
  repositories:
    - repository: ci_templates
      type: github
      name: nalej/ci-templates
      endpoint: nalej

jobs:
- job: DeployComponent
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - template: git/setup.yaml@ci_templates
    parameters:
      sshHostName: $(hostName)
      sshPublicKey: $(sshPublicKey)
  
  - script: |
      MERGE_NUMBER=1
      GITLASTCOMMIT=$(Build.SourceVersion)
      GITLASTMERGECOMMIT=$(git log --merges -n $MERGE_NUMBER --pretty=format:"%H")
      if [ "$GITLASTCOMMIT" == "$GITLASTMERGECOMMIT" ]; then
        MERGE_NUMBER=$(( $MERGE_NUMBER + 1))
      fi
      FOUND_MERGE=0
      while [ $FOUND_MERGE -eq 0 ]; do
        MERGELOG=$(git log --merges -n $MERGE_NUMBER --pretty=format:"%s" | awk -v nr="$MERGE_NUMBER" '{if (NR==nr) print $0}')
        if [[ "$MERGELOG" == *"Merge branch 'master' into"* ]]; then
          MERGE_NUMBER=$(( $MERGE_NUMBER + 1))
        else
          GITLASTMERGECOMMIT=$(git log --merges -n $MERGE_NUMBER --pretty=format:"%H" | awk -v nr="$MERGE_NUMBER" '{if (NR==nr) print $0}')
          echo '##vso[task.setvariable variable=mergeCommit]'$GITLASTMERGECOMMIT
          FOUND_MERGE=1
        fi
      done
      echo "Looking for differences between $GITLASTMERGECOMMIT (last merge commit) and $GITLASTCOMMIT (HEAD commit)"
    displayName: Look for the last real merge commit
  
  - script: |
      MODIFIEDDIRS=$(git diff --name-only $(Build.SourceVersion) $(mergeCommit) | grep "^.*\/.*.proto$" | awk -F/ '{print $1}')
      echo '##vso[task.setvariable variable=modifiedDirectories]'$MODIFIEDDIRS
      if [ "$MODIFIEDDIRS" == "" ]; then
        echo "No modified directories detected"
      else
        echo "Detected directories to generate:"
        echo $MODIFIEDDIRS
      fi
    displayName: Get changed protobuf directories from last merge until now
  
  - script: |
      ls -la $(system.defaultWorkingDirectory)
      # for protobuf in $(modifiedDirectories); do
      #   cd $protobuf
      #   if [ -f .protolangs ]; then
      #     while read lang; do
      #       echo "Building $protobuf definitions for $lang language"
            
      #       docker pull namely/protoc-all:1.15 > /dev/null 2>&1
      #       docker run -v $(system.defaultWorkingDirectory):/defs namely/protoc-all:1.15 -d $protobuf -i . -i /usr/local/include/google -o $protobuf/pb-$lang -l $lang --with-docs --with-gateway
      #     done < .protolangs
      #   fi
      # done
    displayName: Generate protobufs for the modified directories
    condition: and(succeeded(), ne(variables['modifiedDirectories'], ''))
